### PR TITLE
Make it work in native

### PR DESCRIPTION
**Pull request by Sanne**
Quick hack, definitely needs some polishing; mainly you shouldn't need the `reflect-config.json` file - I should fold those rules into the Quarkus H2 extensions.

Compile with:

> mvn package -DskipTests -Dnative

run:

> ./target/pockets-cli-199-SNAPSHOT-runner

Requires a recent Quarkus `main` build locally (depends on version `999-SNAPSHOT`).

### CODE REVIEW

**Comment by Sanne** [comment]
@ebullient sent a second PR to Quarkus https://github.com/quarkusio/quarkus/pull/28492 which makes the `reflect-config.son` which I had included in the first draft unnecessary : stuff is now computed dynamically.

**Comment by Sanne** [comment]
Rebased and refreshed the draft.

**Comment by Sanne** [comment]
Added one more commit, which makes it unnecessary to include the json files in the native version.

**Comment by ebullient** [comment]
Has this delivered in 2.14?

**Comment by Sanne** [comment]
Yes - updated the PR :)

**Review by ebullient — APPROVED** [review]

**Pull request merged**
